name: Backport
on:
  push:
    branches:
      - main
      - v1
jobs:
  backport:
    name: Auto-backport
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Auto-backport changes to v1
        run: |
          set -euxo pipefail
          git checkout main
          git log --left-right --graph --cherry-pick --oneline origin/v1..main -- | awk ' { print $2 } ' >/tmp/git.log
          for COMMITID in $(cat /tmp/git.log | tail -n 1); do
            if [ "$(git branch --list backport/${COMMITID} | wc -l)" -eq 0 ]; then
              TITLE=$(git log --format=%B -n 1 6e0b91426aaaaf681023a7fc2088729676dd6b0b | head -n 1)
              echo "Creating backport PR for ${COMMITID}: ${TITLE}..."
              git config user.name "GitHub Actions"
              git config user.email noreply@github.com
              git checkout v1
              git checkout -b backport/${COMMITID}
              git cherry-pick ${COMMITID}
              git push -u origin backport/${COMMITID}
              gh pr create --title "Backport: ${TITLE}" --body "This is an automatically created PR. Please do not update the branches manually." --base v1 --head backport/${COMMITID}
            else
              echo "Backport for ${COMMITID} already exists, skipping..."
            fi
          done